<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Hesap Bilgileri',
    'Action' => 'Aksiyon',
    'Add to Cart' => 'Sepete ekle',
    'Address' => 'Adres',
    'Address information' => 'Adres bilgisi',
    'Are you sure you want to remove this product from cart?' => 'Bu ürünü sepetten çıkarmak istediğinizden emin misiniz?',
    'Auth Key' => 'Yetkilendirme Anahtarı',
    'Cart' => 'Araba',
    'Checkout' => 'Ödeme',
    'City' => 'Kent',
    'Country' => 'ülke',
    'Created At' => 'Oluşturma Tarihi',
    'Created By' => 'Tarafından yaratıldı',
    'Delete' => 'Sil',
    'Description' => 'Açıklama',
    'Email' => 'E-posta',
    'Firstname' => 'İsim',
    'ID' => 'İD',
    'If you forgot your password you can {0}' => 'Şifrenizi unuttuysanız, şunları yapabilirsiniz: {0}',
    'Image' => 'Resim',
    'Is Admin' => 'Yönetici',
    'Lastname' => 'Soyadı',
    'Login' => 'Oturum aç',
    'Logout' => 'Çıkış Yap',
    'Name' => 'Isim',
    'Need new verification email?' => 'Yeni doğrulama e-postasına mı ihtiyacınız var?',
    'Order ID' => 'Sipariş Kimliği',
    'Password' => 'Parola',
    'Password Hash' => 'Şifre Karması',
    'Password Reset Token' => 'Şifre Sıfırlama Simgesi',
    'Paypal Order ID' => 'Paypal Sipariş Kimliği',
    'Please choose your new password:' => 'Lütfen yeni şifrenizi seçin:',
    'Please contact us if you think this is a server error. Thank you.' => 'Bunun bir sunucu hatası olduğunu düşünüyorsanız lütfen bizimle iletişime geçin. Teşekkür ederim.',
    'Please fill out the following fields to login:' => 'Giriş yapmak için lütfen aşağıdaki alanları doldurun:',
    'Please fill out the following fields to signup:' => 'Kaydolmak için lütfen aşağıdaki alanları doldurun:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Lütfen e-postanızı doldurun. Orada şifre sıfırlamak için bir bağlantı gönderilecektir.',
    'Please fill out your email. A verification email will be sent there.' => 'Lütfen e-postanızı doldurun. Orada bir doğrulama e-postası gönderilecektir.',
    'Price' => 'Fiyat',
    'Product' => 'Ürün',
    'Product ID' => 'ürün kimliği',
    'Product Image' => 'Ürün resmi',
    'Product Name' => 'Ürün adı',
    'Products' => 'Ürün:% s',
    'Profile' => 'Profil',
    'Published' => 'Yayınlanan',
    'Quantity' => 'Miktar',
    'Remember Me' => 'Beni Hatırla',
    'Resend' => 'Yeniden gönder',
    'Reset it' => 'Sıfırla',
    'Save' => 'Kayıt etmek',
    'Send' => 'Gönder',
    'Signup' => 'Kaydol',
    'State' => 'Durum',
    'Status' => 'Durum',
    'Thanks for your business' => 'işiniz için teşekkürler',
    'The above error occurred while the Web server was processing your request' => 'Web sunucusu isteğinizi işlerken yukarıdaki hata oluştu',
    'There are no items in the cart' => 'Sepetinizde hiçbir ürün bulunmamaktadır',
    'Total Items' => 'Tüm nesneler',
    'Total Price' => 'Toplam fiyat',
    'Transaction ID' => 'İşlem Kimliği',
    'Unit Price' => 'Birim fiyat',
    'Update' => 'Güncelleme',
    'Updated At' => 'Güncellenme Tarihi',
    'Updated By' => 'Tarafından güncellendi',
    'User ID' => 'Kullanıcı kimliği',
    'Username' => 'Kullanıcı adı',
    'Verification Token' => 'Doğrulama Simgesi',
    'Welcome {0}' => 'Hoş Geldiniz {0}',
    'Your account was successfully updated' => 'Hesabınız başarıyla güncellendi',
    'Your address was successfully updated' => 'Adresiniz başarıyla güncellendi',
    'Your cart items' => 'Sepetinizdeki ürünler',
    'ZipCode' => 'Posta kodu',
];
