<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Informations sur le compte',
    'Action' => 'Action',
    'Add to Cart' => 'Ajouter au panier',
    'Address' => 'Adresse',
    'Address information' => 'Informations sur l\'adresse',
    'Are you sure you want to remove this product from cart?' => 'Êtes-vous sûr de vouloir retirer ce produit du panier ?',
    'Auth Key' => 'Clé d\'authentification',
    'Cart' => 'Panier',
    'Checkout' => 'Commander',
    'City' => 'Ville',
    'Country' => 'Pays',
    'Created At' => 'Créé à',
    'Created By' => 'Créé par',
    'Delete' => 'Supprimer',
    'Description' => 'Description',
    'Email' => 'Courriel',
    'Firstname' => 'Prénom',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'Si vous avez oublié votre mot de passe, vous pouvez {0}',
    'Image' => 'Image',
    'Is Admin' => 'Est Admin',
    'Lastname' => 'Nom de famille',
    'Login' => 'Connexion',
    'Logout' => 'Déconnexion',
    'Name' => 'Nom',
    'Need new verification email?' => 'Besoin d\'un nouvel email de vérification?',
    'Order ID' => 'Numéro de commande',
    'Password' => 'Mot de passe',
    'Password Hash' => 'Hachage du mot de passe',
    'Password Reset Token' => 'Jeton de réinitialisation du mot de passe',
    'Paypal Order ID' => 'ID de commande Paypal',
    'Please choose your new password:' => 'Veuillez choisir votre nouveau mot de passe:',
    'Please contact us if you think this is a server error. Thank you.' => 'Veuillez nous contacter si vous pensez qu\'il s\'agit d\'une erreur de serveur. Merci. ',
    'Please fill out the following fields to login:' => 'Veuillez remplir les champs suivants pour vous connecter:',
    'Please fill out the following fields to signup:' => 'Veuillez remplir les champs suivants pour vous inscrire:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Veuillez remplir votre adresse e-mail. Un lien pour réinitialiser le mot de passe y sera envoyé.',
    'Please fill out your email. A verification email will be sent there.' => 'Veuillez remplir votre adresse e-mail. Un e-mail de vérification vous sera envoyé.',
    'Price' => 'Prix',
    'Product' => 'Produit',
    'Product ID' => 'ID du produit',
    'Product Image' => 'Image du produit',
    'Product Name' => 'Nom du produit',
    'Products' => 'Produits',
    'Profile' => 'Profil',
    'Published' => 'Publié',
    'Quantity' => 'Quantité',
    'Remember Me' => 'Se souvenir de moi',
    'Resend' => 'Renvoyer',
    'Reset it' => 'Réinitialiser',
    'Save' => 'Enregistrer',
    'Send' => 'Envoyer',
    'Signup' => 'S\'inscrire',
    'State' => 'État',
    'Status' => 'Statut',
    'Thanks for your business' => 'Merci pour votre entreprise',
    'The above error occurred while the Web server was processing your request' => 'L\'erreur ci-dessus s\'est produite pendant que le serveur Web traitait votre demande.',
    'There are no items in the cart' => 'Il n\'y a aucun article dans le panier',
    'Total Items' => 'Total des articles',
    'Total Price' => 'Prix total',
    'Transaction ID' => 'ID de la transaction',
    'Unit Price' => 'Prix unitaire',
    'Update' => 'Mise à jour',
    'Updated At' => 'Mis à jour à',
    'Updated By' => 'Mis à jour par',
    'User ID' => 'ID de l\'utilisateur',
    'Username' => 'Nom d\'utilisateur',
    'Verification Token' => 'Jeton de vérification',
    'Welcome {0}' => 'Bienvenue {0}',
    'Your account was successfully updated' => 'Votre compte a été mis à jour avec succès',
    'Your address was successfully updated' => 'Votre adresse a été mise à jour avec succès',
    'Your cart items' => 'Les articles de votre panier',
    'ZipCode' => 'Code postal',
];
