<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Informações sobre a conta',
    'Action' => 'Ação',
    'Add to Cart' => 'Adicionar ao carrinho',
    'Address' => 'Endereço',
    'Address information' => 'Informações de endereço',
    'Are you sure you want to remove this product from cart?' => 'Você tem certeza de que quer remover este produto do carrinho?',
    'Auth Key' => 'Chave Auth',
    'Cart' => 'Carrinho',
    'Checkout' => 'Checkout',
    'City' => 'Cidade',
    'Country' => 'País',
    'Created At' => 'Criado em',
    'Created By' => 'Criado por',
    'Delete' => 'Excluir',
    'Description' => 'Descrição',
    'Email' => 'Email',
    'Firstname' => 'Primeiro nome',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'Se você esqueceu sua senha, você pode {0}',
    'Image' => 'Imagem',
    'Is Admin' => 'É Admin',
    'Lastname' => 'Sobrenome',
    'Login' => 'Login',
    'Logout' => 'Logout',
    'Name' => 'Nome',
    'Need new verification email?' => 'Precisa de um novo e-mail de verificação?',
    'Order ID' => 'ID do pedido',
    'Password' => 'Senha',
    'Password Hash' => 'Senha Hash',
    'Password Reset Token' => 'Ficha de Reinicialização de Senha',
    'Paypal Order ID' => 'Paypal Order ID',
    'Please choose your new password:' => 'Por favor, escolha sua nova senha:',
    'Please contact us if you think this is a server error. Thank you.' => 'Por favor, entre em contato conosco se você achar que isto é um erro de servidor. Obrigado.',
    'Please fill out the following fields to login:' => 'Por favor, preencha os seguintes campos para fazer o login:',
    'Please fill out the following fields to signup:' => 'Por favor, preencha os seguintes campos para se cadastrar:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Por favor, preencha o seu e-mail. Um link para redefinir a senha será enviado para lá.',
    'Please fill out your email. A verification email will be sent there.' => 'Por favor, preencha o seu e-mail. Um e-mail de verificação será enviado para lá.',
    'Price' => 'Preço',
    'Product' => 'Produto',
    'Product ID' => 'Identificação do produto',
    'Product Image' => 'Imagem do produto',
    'Product Name' => 'Nome do produto',
    'Products' => 'Produtos',
    'Profile' => 'Perfil',
    'Published' => 'Publicado em',
    'Quantity' => 'Quantidade',
    'Remember Me' => 'Lembre-se de mim',
    'Resend' => 'Enviar novamente',
    'Reset it' => 'Restabeleça-o',
    'Save' => 'Salvar',
    'Send' => 'Enviar',
    'Signup' => 'Cadastre-se',
    'State' => 'Estado',
    'Status' => 'Status',
    'Thanks for your business' => 'Obrigado por seu negócio',
    'The above error occurred while the Web server was processing your request' => 'O erro acima ocorreu enquanto o servidor Web estava processando seu pedido',
    'There are no items in the cart' => 'Não há itens no carrinho',
    'Total Items' => 'Total de itens',
    'Total Price' => 'Preço total',
    'Transaction ID' => 'ID da transação',
    'Unit Price' => 'Preço unitário',
    'Update' => 'Atualização',
    'Updated At' => 'Atualizado em',
    'Updated By' => 'Atualizado por',
    'User ID' => 'Identificação do usuário',
    'Username' => 'Nome de usuário',
    'Verification Token' => 'Ficha de verificação',
    'Welcome {0}' => 'Bem-vindo {0}',
    'Your account was successfully updated' => 'Sua conta foi atualizada com sucesso',
    'Your address was successfully updated' => 'Seu endereço foi atualizado com sucesso',
    'Your cart items' => 'Seus itens de carrinho',
    'ZipCode' => 'ZipCode',
];
