<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Información de la cuenta',
    'Action' => 'Acciones',
    'Add to Cart' => 'Añadir al carrito',
    'Address' => 'Dirección',
    'Address information' => 'Información de dirección',
    'Are you sure you want to remove this product from cart?' => '¿Está seguro de que desea eliminar este producto del carrito?',
    'Auth Key' => 'Clave de autentificación',
    'Cart' => 'Carrito',
    'Checkout' => 'Continua compra',
    'City' => 'Ciudad',
    'Country' => 'País',
    'Created At' => 'Fecha de creación',
    'Created By' => 'Creado por',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Email' => 'Correo electrónico',
    'Firstname' => 'Nombre',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'Si has olvidado tu contraseña puedes {0}',
    'Image' => 'Imagen',
    'Is Admin' => 'Es administrador',
    'Lastname' => 'Apellido',
    'Login' => 'Iniciar sesión',
    'Logout' => 'Cerrar la sesión',
    'Name' => 'Nombre',
    'Need new verification email?' => '¿Necesita un nuevo correo electrónico de verificación?',
    'Order ID' => 'ID de pedido',
    'Password' => 'Contraseña',
    'Password Hash' => 'Hash de contraseña',
    'Password Reset Token' => 'Token de restablecimiento de contraseña',
    'Paypal Order ID' => 'ID de pedido de Paypal',
    'Please choose your new password:' => 'Por favor, elija su nueva contraseña:',
    'Please contact us if you think this is a server error. Thank you.' => 'Por favor, póngase en contacto con nosotros si cree que se trata de un error del servidor. Gracias.',
    'Please fill out the following fields to login:' => 'Por favor, rellene los siguientes campos para iniciar sesión:',
    'Please fill out the following fields to signup:' => 'Por favor, rellene los siguientes campos para registrarse:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Por favor, rellene su correo electrónico. Allí se enviará un enlace para restablecer la contraseña.',
    'Please fill out your email. A verification email will be sent there.' => 'Por favor, rellene su correo electrónico. Se enviará un correo electrónico de verificación.',
    'Price' => 'Precio',
    'Product' => 'Producto',
    'Product ID' => 'ID del producto',
    'Product Image' => 'Imagen del producto',
    'Product Name' => 'Nombre del producto',
    'Products' => 'Productos',
    'Profile' => 'Perfil',
    'Published' => 'Publicado',
    'Quantity' => 'Cantidad',
    'Remember Me' => 'Recuérdame',
    'Resend' => 'Reenviar',
    'Reset it' => 'Restablecer',
    'Save' => 'Guardar',
    'Send' => 'Enviar',
    'Signup' => 'Registrarse',
    'State' => 'Estado',
    'Status' => 'Estado',
    'Thanks for your business' => 'Gracias por su compra',
    'The above error occurred while the Web server was processing your request' => 'El error se produjo mientras el servidor web procesaba su solicitud',
    'There are no items in the cart' => 'No hay artículos en el carrito',
    'Total Items' => 'Total de artículos',
    'Total Price' => 'Precio total',
    'Transaction ID' => 'ID de la transacción',
    'Unit Price' => 'Precio unitario',
    'Update' => 'Actualizar',
    'Updated At' => 'Actualizado en',
    'Updated By' => 'Actualizado por',
    'User ID' => 'ID de usuario',
    'Username' => 'Nombre de usuario',
    'Verification Token' => 'Token de verificación',
    'Welcome {0}' => 'Bienvenido {0}',
    'Your account was successfully updated' => 'Su cuenta ha sido actualizada con éxito',
    'Your address was successfully updated' => 'Su dirección ha sido actualizada con éxito',
    'Your cart items' => 'Los artículos de su carrito',
    'ZipCode' => 'Código postal',
];
