<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Informacje o rachunku',
    'Action' => 'Akcja',
    'Add to Cart' => 'Dodaj do koszyka',
    'Address' => 'Adres',
    'Address information' => 'Informacje o adresie',
    'Are you sure you want to remove this product from cart?' => 'Czy na pewno chcesz usunąć ten produkt z koszyka?',
    'Auth Key' => 'Klucz autoryzacji',
    'Cart' => 'Koszyk',
    'Checkout' => 'Checkout',
    'City' => 'Miasto',
    'Country' => 'Kraj',
    'Created At' => 'Utworzono w',
    'Created By' => 'Utworzony przez',
    'Delete' => 'Usuń',
    'Description' => 'Opis',
    'Email' => 'Email',
    'Firstname' => 'Imię i nazwisko',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'Jeśli zapomniałeś hasła, możesz {0}',
    'Image' => 'Obrazek',
    'Is Admin' => 'Jest adminem',
    'Lastname' => 'Lastname',
    'Login' => 'Login',
    'Logout' => 'Logout',
    'Name' => 'Nazwa',
    'Need new verification email?' => 'Potrzebujesz nowego emaila weryfikacyjnego?',
    'Order ID' => 'ID zamówienia',
    'Password' => 'Hasło',
    'Password Hash' => 'Hash hasła',
    'Password Reset Token' => 'Token resetowania hasła',
    'Paypal Order ID' => 'Identyfikator zamówienia Paypal',
    'Please choose your new password:' => 'Proszę wybrać nowe hasło:',
    'Please contact us if you think this is a server error. Thank you.' => 'Prosimy o kontakt, jeśli uważasz, że jest to błąd serwera. Dziękujemy.',
    'Please fill out the following fields to login:' => 'Proszę wypełnić następujące pola, aby się zalogować:',
    'Please fill out the following fields to signup:' => 'Proszę wypełnić poniższe pola, aby się zarejestrować:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Proszę wypełnić swój e-mail. Link do resetowania hasła zostanie tam wysłany.',
    'Please fill out your email. A verification email will be sent there.' => 'Proszę wypełnić swój e-mail. Zostanie wysłany e-mail weryfikacyjny.',
    'Price' => 'Cena',
    'Product' => 'Produkt',
    'Product ID' => 'ID produktu',
    'Product Image' => 'Obraz produktu',
    'Product Name' => 'Nazwa produktu',
    'Products' => 'Produkty',
    'Profile' => 'Profil',
    'Published' => 'Opublikowano',
    'Quantity' => 'Ilość',
    'Remember Me' => 'Zapamiętaj mnie',
    'Resend' => 'Wyślij ponownie',
    'Reset it' => 'Zresetuj',
    'Save' => 'Zresetuj',
    'Send' => 'Wyślij',
    'Signup' => 'Zarejestruj się',
    'State' => 'Stan',
    'Status' => 'Status',
    'Thanks for your business' => 'Dziękujemy za współpracę',
    'The above error occurred while the Web server was processing your request' => 'Powyższy błąd wystąpił podczas przetwarzania żądania przez serwer WWW.',
    'There are no items in the cart' => 'Nie ma żadnych pozycji w koszyku',
    'Total Items' => 'Suma pozycji',
    'Total Price' => 'Cena całkowita',
    'Transaction ID' => 'ID transakcji',
    'Unit Price' => 'Cena jednostkowa',
    'Update' => 'Aktualizacja',
    'Updated At' => 'Zaktualizowano w',
    'Updated By' => 'Zaktualizowana przez',
    'User ID' => 'Identyfikator użytkownika',
    'Username' => 'Nazwa użytkownika',
    'Verification Token' => 'Token weryfikacyjny',
    'Welcome {0}' => 'Witamy {0}',
    'Your account was successfully updated' => 'Twoje konto zostało pomyślnie zaktualizowane',
    'Your address was successfully updated' => 'Twój adres został pomyślnie zaktualizowany',
    'Your cart items' => 'Twoje pozycje w koszyku',
    'ZipCode' => 'Kod pocztowy',
];
