<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => '',
    'Action' => '',
    'Add to Cart' => '',
    'Address' => '',
    'Address information' => '',
    'Are you sure you want to remove this product from cart?' => '',
    'Auth Key' => '',
    'Cart' => '',
    'Checkout' => '',
    'City' => '',
    'Country' => '',
    'Created At' => '',
    'Created By' => '',
    'Created_at' => '',
    'Delete' => '',
    'Description' => '',
    'Email' => '',
    'Firstname' => '',
    'I' => '',
    'ID' => '',
    'If you forgot your password you can {0}' => '',
    'Image' => '',
    'Is Admin' => '',
    'Lastname' => '',
    'Login' => '',
    'Logout' => '',
    'Name' => '',
    'Need new verification email?' => '',
    'Order ID' => '',
    'Password' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Paypal Order ID' => '',
    'Please choose your new password:' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out the following fields to login' => '',
    'Please fill out the following fields to signup:' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Please fill out your email. A verification email will be sent there.' => '',
    'Price' => '',
    'Product' => '',
    'Product ID' => '',
    'Product Image' => '',
    'Product Name' => '',
    'Products' => '',
    'Profile' => '',
    'Published' => '',
    'Quantity' => '',
    'Remember Me' => '',
    'Resend' => '',
    'Save' => '',
    'Send' => '',
    'Signup' => '',
    'State' => '',
    'Status' => '',
    'Thanks for your business' => '',
    'The above error occurred while the Web server was processing your request' => '',
    'There are no items in the cart' => '',
    'Total Items' => '',
    'Total Price' => '',
    'Transaction ID' => '',
    'Unit Price' => '',
    'Update' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Updated_at' => '',
    'User ID' => '',
    'Username' => '',
    'Verification Token' => '',
    'Welcome {0}' => '',
    'Your account was successfully updated' => '',
    'Your address was successfully updated' => '',
    'Your cart items' => '',
    'ZipCode' => '',
    'Zipcode' => '',
    'reset it' => '',
];
