<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Ანგარიშის ინფორმაცია',
    'Action' => 'მოქმედება',
    'Add to Cart' => 'Კალათაში დამატება',
    'Address' => 'მისამართი',
    'Address information' => 'მისამართის ინფორმაცია',
    'Are you sure you want to remove this product from cart?' => 'დარწმუნებული ხართ, რომ გსურთ ამ პროდუქტის კალათიდან ამოღება?',
    'Auth Key' => 'ავტორი გასაღები',
    'Cart' => 'კალათა',
    'Checkout' => 'გადახდა',
    'City' => 'ქალაქი',
    'Country' => 'ქვეყანა',
    'Created At' => 'შექმნილია ატ',
    'Created By' => 'Შექმნილია მიერ',
    'Delete' => 'წაშლა',
    'Description' => 'აღწერა',
    'Email' => 'ელ.ფოსტა',
    'Firstname' => 'Სახელი',
    'ID' => 'პირადობის მოწმობა',
    'If you forgot your password you can {0}' => 'თუ დაგავიწყდათ პაროლი, შეგიძლიათ {0}',
    'Image' => 'სურათი',
    'Is Admin' => 'არის ადმინ',
    'Lastname' => 'Გვარი',
    'Login' => 'Შესვლა',
    'Logout' => 'გასვლა',
    'Name' => 'სახელი',
    'Need new verification email?' => 'გჭირდებათ ახალი დამადასტურებელი ელ.წერილი?',
    'Order ID' => 'შეკვეთის ნომერი',
    'Password' => 'პაროლი',
    'Password Hash' => 'პაროლი Hash',
    'Password Reset Token' => 'პაროლის აღდგენის ნიშანი',
    'Paypal Order ID' => 'Paypal შეკვეთის ID',
    'Please choose your new password:' => 'გთხოვთ, აირჩიოთ თქვენი ახალი პაროლი:',
    'Please contact us if you think this is a server error. Thank you.' => 'გთხოვთ, დაგვიკავშირდეთ, თუ თვლით, რომ ეს სერვერის შეცდომაა. Გმადლობთ.',
    'Please fill out the following fields to login:' => 'გთხოვთ, შეავსოთ შემდეგი ველები შესასვლელად:',
    'Please fill out the following fields to signup:' => 'რეგისტრაციისთვის გთხოვთ შეავსოთ შემდეგი ველები:',
    'Please fill out your email. A link to reset password will be sent there.' => 'გთხოვთ, შეავსოთ თქვენი ელ.წერილი. პაროლის გადატვირთვის ბმული იქ გაიგზავნება.',
    'Please fill out your email. A verification email will be sent there.' => 'გთხოვთ, შეავსოთ თქვენი ელ.წერილი. დამადასტურებელი ელ.ფოსტა იქ გაიგზავნება.',
    'Price' => 'ფასი',
    'Product' => 'პროდუქტი',
    'Product ID' => 'პროდუქტის ID',
    'Product Image' => 'პროდუქტის სურათი',
    'Product Name' => 'Პროდუქტის სახელი',
    'Products' => 'პროდუქტები',
    'Profile' => 'პროფილი',
    'Published' => 'გამოქვეყნებულია',
    'Quantity' => 'რაოდენობა',
    'Remember Me' => 'Დამიმახსოვრე',
    'Resend' => 'Ხელახლა გაგზავნა',
    'Reset it' => 'გადააყენე იგი',
    'Save' => 'Გადარჩენა',
    'Send' => 'გაგზავნა',
    'Signup' => 'დარეგისტრირება',
    'State' => 'სახელმწიფო',
    'Status' => 'სტატუსი',
    'Thanks for your business' => 'მადლობა თქვენი ბიზნესისთვის',
    'The above error occurred while the Web server was processing your request' => 'ზემოხსენებული შეცდომა მოხდა, როდესაც ვებ სერვერი ამუშავებდა თქვენს მოთხოვნას',
    'There are no items in the cart' => 'კალათაში არ არის საქონელი',
    'Total Items' => 'სულ ნივთები',
    'Total Price' => 'Ჯამური ღირებულება',
    'Transaction ID' => 'გარიგების ID',
    'Unit Price' => 'Ერთეულის ფასი',
    'Update' => 'განახლება',
    'Updated At' => 'განახლებულია At',
    'Updated By' => 'განახლებულია ავტორი',
    'User ID' => 'მომხმარებლის იდენტიფიკაცია',
    'Username' => 'მომხმარებლის სახელი',
    'Verification Token' => 'ვერიფიკაციის ნიშანი',
    'Welcome {0}' => 'მოგესალმებით {0}',
    'Your account was successfully updated' => 'თქვენი ანგარიში წარმატებით განახლდა',
    'Your address was successfully updated' => 'თქვენი მისამართი წარმატებით განახლდა',
    'Your cart items' => 'თქვენი კალათის საგნები',
    'ZipCode' => 'Ზიპ კოდი',
];
