<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'アカウント情報',
    'Action' => 'アクション',
    'Add to Cart' => 'カートに入れる',
    'Address' => 'アドレス',
    'Address information' => 'アドレス情報',
    'Are you sure you want to remove this product from cart?' => 'この商品をカートから削除してよろしいですか？',
    'Auth Key' => '認証キー',
    'Cart' => 'カート',
    'Checkout' => 'チェックアウト',
    'City' => '市町村',
    'Country' => '国',
    'Created At' => '作成日',
    'Created By' => '作成者',
    'Delete' => '削除',
    'Description' => '説明',
    'Email' => '電子メール',
    'Firstname' => 'ファーストネーム',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'パスワードを忘れた場合は、{0}をクリックしてください。',
    'Image' => '画像',
    'Is Admin' => '管理者',
    'Lastname' => '名字',
    'Login' => 'ログイン',
    'Logout' => 'ログアウト',
    'Name' => '名前',
    'Need new verification email?' => '新しい認証メールが必要ですか？',
    'Order ID' => 'オーダーID',
    'Password' => 'パスワード',
    'Password Hash' => 'パスワードハッシュ',
    'Password Reset Token' => 'パスワードリセットトークン',
    'Paypal Order ID' => 'ペイパルオーダーID',
    'Please choose your new password:' => '新しいパスワードを選択してください。',
    'Please contact us if you think this is a server error. Thank you.' => 'サーバーエラーと思われる場合は、お問い合わせください。ありがとうございました。',
    'Please fill out the following fields to login:' => 'ログインするには、以下の項目を入力してください。',
    'Please fill out the following fields to signup:' => 'サインアップするには、以下の項目を入力してください。',
    'Please fill out your email. A link to reset password will be sent there.' => 'Eメールを入力してください。パスワードをリセットするためのリンクがそこに送られます。',
    'Please fill out your email. A verification email will be sent there.' => 'あなたのEメールを入力してください。認証メールが送信されます。',
    'Price' => '価格',
    'Product' => '製品名',
    'Product ID' => '商品ID',
    'Product Image' => '商品画像',
    'Product Name' => '商品名',
    'Products' => '製品情報',
    'Profile' => 'プロフィール',
    'Published' => '公開',
    'Quantity' => '数量',
    'Remember Me' => 'リメンバーミー',
    'Resend' => '再送',
    'Reset it' => 'リセット',
    'Save' => '保存',
    'Send' => '送る',
    'Signup' => '会員登録',
    'State' => '状態',
    'Status' => 'ステータス',
    'Thanks for your business' => 'ご利用ありがとうございました。',
    'The above error occurred while the Web server was processing your request' => 'Webサーバーがお客様のリクエストを処理中に上記のエラーが発生しました。。',
    'There are no items in the cart' => 'カートに商品がありません。',
    'Total Items' => '商品合計',
    'Total Price' => '合計金額',
    'Transaction ID' => 'トランザクションID',
    'Unit Price' => '販売価格',
    'Update' => '更新日',
    'Updated At' => '更新日',
    'Updated By' => '更新日',
    'User ID' => 'ユーザーID',
    'Username' => 'ユーザー名',
    'Verification Token' => '認証トークン',
    'Welcome {0}' => 'ようこそ{0}。',
    'Your account was successfully updated' => 'アカウントの更新に成功しました。',
    'Your address was successfully updated' => 'お客様の住所が正しく更新されました。',
    'Your cart items' => 'カートの中身',
    'ZipCode' => '郵便番号',
];
