<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'معلومات الحساب',
    'Action' => 'عمل',
    'Add to Cart' => 'أضف إلى السلة',
    'Address' => 'عنوان',
    'Address information' => 'معلومات العنوان',
    'Are you sure you want to remove this product from cart?' => 'هل أنت متأكد أنك تريد إزالة هذا المنتج من سلة التسوق؟',
    'Auth Key' => 'مفتاح المصادقة',
    'Cart' => 'عربة التسوق',
    'Checkout' => 'الدفع',
    'City' => 'مدينة',
    'Country' => 'دولة',
    'Created At' => 'أنشئت في',
    'Created By' => 'انشأ من قبل',
    'Delete' => 'حذف',
    'Description' => 'وصف',
    'Email' => 'بريد إلكتروني',
    'Firstname' => 'الاسم الأول',
    'ID' => 'هوية شخصية',
    'If you forgot your password you can {0}' => 'إذا نسيت كلمة مرورك ، فيمكنك {0}',
    'Image' => 'صورة',
    'Is Admin' => 'هو الادارية',
    'Lastname' => 'الكنية',
    'Login' => 'تسجيل الدخول',
    'Logout' => 'تسجيل خروج',
    'Name' => 'اسم',
    'Need new verification email?' => 'هل تحتاج إلى بريد إلكتروني جديد للتحقق؟',
    'Order ID' => 'رقم التعريف الخاص بالطلب',
    'Password' => 'كلمه السر',
    'Password Hash' => 'تجزئة كلمة المرور',
    'Password Reset Token' => 'رمز اعادة كلمة المرور',
    'Paypal Order ID' => 'معرف طلب Paypal',
    'Please choose your new password:' => 'الرجاء اختيار كلمة المرور الجديدة الخاصة بك:',
    'Please contact us if you think this is a server error. Thank you.' => 'يرجى الاتصال بنا إذا كنت تعتقد أن هذا خطأ في الخادم. شكرا لك.',
    'Please fill out the following fields to login:' => 'يرجى ملء الحقول التالية لتسجيل الدخول:',
    'Please fill out the following fields to signup:' => 'يرجى ملء الحقول التالية للتسجيل:',
    'Please fill out your email. A link to reset password will be sent there.' => 'يرجى ملء البريد الإلكتروني الخاص بك. سيتم إرسال رابط لإعادة تعيين كلمة المرور هناك.',
    'Please fill out your email. A verification email will be sent there.' => 'يرجى ملء البريد الإلكتروني الخاص بك. سيتم إرسال بريد إلكتروني للتحقق هناك.',
    'Price' => 'سعر',
    'Product' => 'منتج',
    'Product ID' => 'معرف المنتج',
    'Product Image' => 'صورة المنتج',
    'Product Name' => 'اسم المنتج',
    'Products' => 'منتجات',
    'Profile' => 'الملف الشخصي',
    'Published' => 'نشرت',
    'Quantity' => 'كمية',
    'Remember Me' => 'تذكرنى',
    'Resend' => 'إعادة إرسال',
    'Reset it' => 'إعادة تعيينها',
    'Save' => 'يحفظ',
    'Send' => 'إرسال',
    'Signup' => 'اشتراك',
    'State' => 'حالة',
    'Status' => 'حالة',
    'Thanks for your business' => 'شكرا لعملك',
    'The above error occurred while the Web server was processing your request' => 'حدث الخطأ أعلاه أثناء معالجة خادم الويب لطلبك',
    'There are no items in the cart' => 'لا توجد بنود في عربة',
    'Total Items' => 'إجمالي العناصر',
    'Total Price' => 'السعر الكلي',
    'Transaction ID' => 'رقم المعاملة',
    'Unit Price' => 'سعر الوحده',
    'Update' => 'تحديث',
    'Updated At' => 'تم التحديث في',
    'Updated By' => 'تم التحديث بواسطة',
    'User ID' => 'معرف المستخدم',
    'Username' => 'اسم المستخدم',
    'Verification Token' => 'رمز التحقق',
    'Welcome {0}' => 'مرحبًا {0}',
    'Your account was successfully updated' => 'تم تحديث حسابك بنجاح',
    'Your address was successfully updated' => 'تم تحديث عنوانك بنجاح',
    'Your cart items' => 'عناصر عربة التسوق الخاصة بك',
    'ZipCode' => 'الرمز البريدي',
];
