<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Konto-Informationen',
    'Action' => 'Aktion',
    'Add to Cart' => 'Zum Warenkorb hinzufügen',
    'Address' => 'Adresse',
    'Address information' => 'Informationen zur Adresse',
    'Are you sure you want to remove this product from cart?' => 'Sind Sie sicher, dass Sie dieses Produkt aus dem Warenkorb entfernen möchten?',
    'Auth Key' => 'Auth-Schlüssel',
    'Cart' => 'Warenkorb',
    'Checkout' => 'Kasse',
    'City' => 'Stadt',
    'Country' => 'Land',
    'Created At' => 'Erstellt am',
    'Created By' => 'Erstellt von',
    'Delete' => 'Löschen',
    'Description' => 'Beschreibung',
    'Email' => 'E-Mail',
    'Firstname' => 'Vorname',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'Wenn Sie Ihr Passwort vergessen haben, können Sie {0}',
    'Image' => 'Bild',
    'Is Admin' => 'Ist Verwalter',
    'Lastname' => 'Nachname',
    'Login' => 'Anmeldung',
    'Logout' => 'Abmelden',
    'Name' => 'Name',
    'Need new verification email?' => 'Benötigen Sie eine neue Bestätigungs-E-Mail?',
    'Order ID' => 'ID bestellen',
    'Password' => 'Kennwort',
    'Password Hash' => 'Passwort-Hash',
    'Password Reset Token' => 'Passwort zurücksetzen Token',
    'Paypal Order ID' => 'Paypal-Bestell-ID',
    'Please choose your new password:' => 'Bitte wählen Sie Ihr neues Passwort:',
    'Please contact us if you think this is a server error. Thank you.' => 'Bitte kontaktieren Sie uns, wenn Sie glauben, dass dies ein Serverfehler ist. Wir danken Ihnen.',
    'Please fill out the following fields to login:' => 'Bitte füllen Sie die folgenden Felder aus, um sich anzumelden:',
    'Please fill out the following fields to signup:' => 'Bitte füllen Sie die folgenden Felder aus, um sich zu registrieren:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Bitte geben Sie Ihre E-Mail-Adresse an. Ein Link zum Zurücksetzen des Passworts wird dorthin gesendet.',
    'Please fill out your email. A verification email will be sent there.' => 'Bitte geben Sie Ihre E-Mail Adresse an. Eine Bestätigungs-E-Mail wird dorthin gesendet.',
    'Price' => 'Preis',
    'Product' => 'Produkt',
    'Product ID' => 'Produkt-ID',
    'Product Image' => 'Produkt-Bild',
    'Product Name' => 'Produkt-Name',
    'Products' => 'Produkte',
    'Profile' => 'Profil',
    'Published' => 'Veröffentlicht',
    'Quantity' => 'Menge',
    'Remember Me' => 'An mich erinnern',
    'Resend' => 'Erneut senden',
    'Reset it' => 'Zurücksetzen',
    'Save' => 'Speichern',
    'Send' => 'Senden',
    'Signup' => 'Anmeldung',
    'State' => 'Zustand',
    'Status' => 'Status',
    'Thanks for your business' => 'Vielen Dank für Ihr Geschäft',
    'The above error occurred while the Web server was processing your request' => 'Der obige Fehler ist aufgetreten, während der Webserver Ihre Anfrage bearbeitet hat',
    'There are no items in the cart' => 'Es befinden sich keine Artikel im Warenkorb',
    'Total Items' => 'Artikel gesamt',
    'Total Price' => 'Gesamtpreis',
    'Transaction ID' => 'Transaktions-ID',
    'Unit Price' => 'Stückpreis',
    'Update' => 'Aktualisieren',
    'Updated At' => 'Aktualisiert um',
    'Updated By' => 'Aktualisiert von',
    'User ID' => 'Benutzer-ID',
    'Username' => 'Benutzername',
    'Verification Token' => 'Verifizierungs-Token',
    'Welcome {0}' => 'Willkommen {0}',
    'Your account was successfully updated' => 'Ihr Konto wurde erfolgreich aktualisiert',
    'Your address was successfully updated' => 'Ihre Adresse wurde erfolgreich aktualisiert',
    'Your cart items' => 'Ihre Artikel im Warenkorb',
    'ZipCode' => 'Postleitzahl',
];
