<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'खाता संबंधी जानकारी',
    'Action' => 'कार्य',
    'Add to Cart' => 'कार्ट में डालें',
    'Address' => 'पता',
    'Address information' => 'पते की जानकारी',
    'Are you sure you want to remove this product from cart?' => 'क्या आप वाकई इस उत्पाद को कार्ट से हटाना चाहते हैं?',
    'Auth Key' => 'प्रमाणन कुंजी',
    'Cart' => 'कार्ट',
    'Checkout' => 'चेक आउट',
    'City' => 'शहर',
    'Country' => 'देश',
    'Created At' => 'पर बनाया गया',
    'Created By' => 'के द्वारा बनाई गई',
    'Delete' => 'हटाएं',
    'Description' => 'विवरण',
    'Email' => 'ईमेल',
    'Firstname' => 'पहला नाम',
    'ID' => 'ईद',
    'If you forgot your password you can {0}' => 'यदि आप अपना पासवर्ड भूल गए हैं तो आप {0}',
    'Image' => 'छवि',
    'Is Admin' => 'व्यवस्थापक है',
    'Lastname' => 'अंतिम नाम',
    'Login' => 'लॉग इन करें',
    'Logout' => 'लॉग आउट',
    'Name' => 'नाम',
    'Need new verification email?' => 'नए सत्यापन ईमेल की आवश्यकता है?',
    'Order ID' => 'आदेश कामतत्व',
    'Password' => 'कुंजिका',
    'Password Hash' => 'पासवर्ड हैश',
    'Password Reset Token' => 'पासवर्ड रीसेट टोकन',
    'Paypal Order ID' => 'पेपैल आदेश आईडी',
    'Please choose your new password:' => 'कृपया अपना नया पासवर्ड चुनें:',
    'Please contact us if you think this is a server error. Thank you.' => 'कृपया हमसे संपर्क करें यदि आपको लगता है कि यह एक सर्वर त्रुटि है। धन्यवाद।',
    'Please fill out the following fields to login:' => 'लॉग इन करने के लिए कृपया निम्नलिखित फ़ील्ड भरें:',
    'Please fill out the following fields to signup:' => 'साइन अप करने के लिए कृपया निम्नलिखित फ़ील्ड भरें:',
    'Please fill out your email. A link to reset password will be sent there.' => 'कृपया अपना ईमेल भरें। पासवर्ड रीसेट करने के लिए एक लिंक वहां भेजा जाएगा।',
    'Please fill out your email. A verification email will be sent there.' => 'कृपया अपना ईमेल भरें। वहां एक सत्यापन ईमेल भेजा जाएगा।',
    'Price' => 'कीमत',
    'Product' => 'उत्पाद',
    'Product ID' => 'उत्पाद आइ डि',
    'Product Image' => 'उत्पाद का चित्र',
    'Product Name' => 'उत्पाद का नाम',
    'Products' => 'उत्पादों',
    'Profile' => 'प्रोफ़ाइल',
    'Published' => 'प्रकाशित',
    'Quantity' => 'मात्रा',
    'Remember Me' => 'मुझे याद रखें',
    'Resend' => 'पुन: भेजें',
    'Reset it' => 'इसे रीसेट करें',
    'Save' => 'सहेजें',
    'Send' => 'संदेश',
    'Signup' => 'साइन अप करें',
    'State' => 'राज्य',
    'Status' => 'स्थिति',
    'Thanks for your business' => 'आपके व्यवसाय के लिए धन्यवाद',
    'The above error occurred while the Web server was processing your request' => 'उपरोक्त त्रुटि तब हुई जब वेब सर्वर आपके अनुरोध को संसाधित कर रहा था',
    'There are no items in the cart' => 'टोकरे में कोई आइटम नहीं हैं',
    'Total Items' => 'कुल सामान',
    'Total Price' => 'कुल कीमत',
    'Transaction ID' => 'लेन-देन आईडी',
    'Unit Price' => 'यूनिट मूल्य',
    'Update' => 'अपडेट करें',
    'Updated At' => 'अद्यतन किया गया',
    'Updated By' => 'द्वारा अपडेट',
    'User ID' => 'यूज़र आईडी',
    'Username' => 'उपयोगकर्ता नाम',
    'Verification Token' => 'सत्यापन टोकन',
    'Welcome {0}' => 'स्वागत है {0}',
    'Your account was successfully updated' => 'आपका खाता सफलतापूर्वक अपडेट कर दिया गया था',
    'Your address was successfully updated' => 'आपका पता सफलतापूर्वक अपडेट किया गया',
    'Your cart items' => 'आपके कार्ट आइटम',
    'ZipCode' => 'ज़िप कोड',
];
