<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => '帐户信息',
    'Action' => '行动',
    'Add to Cart' => '添加到购物车',
    'Address' => '地址',
    'Address information' => '地址信息',
    'Are you sure you want to remove this product from cart?' => '您确定要从购物车中删除该产品吗？',
    'Auth Key' => '验证码',
    'Cart' => '购物车',
    'Checkout' => '结账',
    'City' => '城市',
    'Country' => '国家',
    'Created At' => '创建于',
    'Created By' => '创建者',
    'Delete' => '删除',
    'Description' => '描述',
    'Email' => '电子邮件',
    'Firstname' => '姓氏',
    'ID' => '身份证',
    'If you forgot your password you can {0}' => '如果你忘记了你的密码，你可以{0}',
    'Image' => '图片',
    'Is Admin' => '是管理员',
    'Lastname' => '姓氏',
    'Login' => '登录',
    'Logout' => '注销',
    'Name' => '名称',
    'Need new verification email?' => '需要新的验证邮件吗？',
    'Order ID' => '订单编号',
    'Password' => '密码',
    'Password Hash' => '密码哈希值',
    'Password Reset Token' => '密码重置令牌',
    'Paypal Order ID' => '支付宝订单ID',
    'Please choose your new password:' => '请选择您的新密码:',
    'Please contact us if you think this is a server error. Thank you.' => '如果你认为这是一个服务器错误，请联系我们。谢谢你。',
    'Please fill out the following fields to login:' => '请填写以下字段来登录:',
    'Please fill out the following fields to signup:' => '请填写以下字段进行注册:',
    'Please fill out your email. A link to reset password will be sent there.' => '请填写您的电子邮件。重置密码的链接将被发送到那里。',
    'Please fill out your email. A verification email will be sent there.' => '请填写您的电子邮件。一封验证邮件将被发送至此。',
    'Price' => '价格',
    'Product' => '产品',
    'Product ID' => '产品ID',
    'Product Image' => '产品图片',
    'Product Name' => '产品名称',
    'Products' => '产品',
    'Profile' => '简介',
    'Published' => '已发布',
    'Quantity' => '数量',
    'Remember Me' => '记住我',
    'Resend' => '重新发送',
    'Reset it' => '重置它',
    'Save' => '保存',
    'Send' => '发送',
    'Signup' => '注册',
    'State' => '状态',
    'Status' => '状态',
    'Thanks for your business' => '感谢你的业务',
    'The above error occurred while the Web server was processing your request' => '网络服务器在处理您的请求时发生了上述错误',
    'There are no items in the cart' => '购物车中没有物品',
    'Total Items' => '项目总数',
    'Total Price' => '总价',
    'Transaction ID' => '交易ID',
    'Unit Price' => '单位价格',
    'Update' => '更新时间',
    'Updated At' => '更新时间',
    'Updated By' => '更新者',
    'User ID' => '用户ID',
    'Username' => '用户名',
    'Verification Token' => '验证码',
    'Welcome {0}' => '欢迎{0}',
    'Your account was successfully updated' => '您的账户已成功更新',
    'Your address was successfully updated' => '您的地址已成功更新',
    'Your cart items' => '您的购物车项目',
    'ZipCode' => '邮编',
];
