<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => '계정 정보',
    'Action' => '동작',
    'Add to Cart' => '장바구니에 담기',
    'Address' => '주소',
    'Address information' => '주소 정보',
    'Are you sure you want to remove this product from cart?' => '이 제품을 장바구니에서 제거 하시겠습니까?',
    'Auth Key' => '인증 키',
    'Cart' => '카트',
    'Checkout' => '점검',
    'City' => '시티',
    'Country' => '국가',
    'Created At' => '만든 날짜',
    'Created By' => '작성자',
    'Delete' => '지우다',
    'Description' => '기술',
    'Email' => '이메일',
    'Firstname' => '이름',
    'ID' => '신분증',
    'If you forgot your password you can {0}' => '비밀번호를 잊은 경우 {0}',
    'Image' => '영상',
    'Is Admin' => '관리자 임',
    'Lastname' => '성',
    'Login' => '로그인',
    'Logout' => '로그 아웃',
    'Name' => '이름',
    'Need new verification email?' => '새 확인 이메일이 필요하십니까?',
    'Order ID' => '주문 아이디',
    'Password' => '암호',
    'Password Hash' => '암호 해시',
    'Password Reset Token' => '비밀번호 재설정 토큰',
    'Paypal Order ID' => 'Paypal 주문 ID',
    'Please choose your new password:' => '새 비밀번호를 선택하십시오:',
    'Please contact us if you think this is a server error. Thank you.' => '서버 오류라고 생각되면 문의 해주세요. 감사합니다.',
    'Please fill out the following fields to login:' => '로그인하려면 다음 필드를 작성하십시오.',
    'Please fill out the following fields to signup:' => '가입하려면 다음 필드를 작성하십시오.',
    'Please fill out your email. A link to reset password will be sent there.' => '이메일을 작성 해주세요. 비밀번호 재설정 링크가 전송됩니다.',
    'Please fill out your email. A verification email will be sent there.' => '이메일을 작성해주세요. 확인 이메일이 전송됩니다.',
    'Price' => '가격',
    'Product' => '생성물',
    'Product ID' => '제품 ID',
    'Product Image' => '제품 이미지',
    'Product Name' => '상품명',
    'Products' => '제품',
    'Profile' => '프로필',
    'Published' => '게시 됨',
    'Quantity' => '수량',
    'Remember Me' => '날 기억해',
    'Resend' => '재전송',
    'Reset it' => '재설정',
    'Save' => '저장',
    'Send' => '보내다',
    'Signup' => '가입하기',
    'State' => '상태',
    'Status' => '상태',
    'Thanks for your business' => '귀하의 비즈니스에 감사드립니다',
    'The above error occurred while the Web server was processing your request' => '웹 서버가 귀하의 요청을 처리하는 동안 위의 오류가 발생했습니다.',
    'There are no items in the cart' => '장바구니에 담긴 상품이 없습니다.',
    'Total Items' => '총 항목',
    'Total Price' => '총 가격',
    'Transaction ID' => '거래 ID',
    'Unit Price' => '단가',
    'Update' => '최신 정보',
    'Updated At' => '업데이트 날짜',
    'Updated By' => '업데이트 자',
    'User ID' => '사용자 ID',
    'Username' => '사용자 이름',
    'Verification Token' => '확인 토큰',
    'Welcome {0}' => '{0} 님, 환영합니다',
    'Your account was successfully updated' => '귀하의 계정이 성공적으로 업데이트되었습니다',
    'Your address was successfully updated' => '주소가 성공적으로 업데이트되었습니다.',
    'Your cart items' => '장바구니 항목',
    'ZipCode' => '우편 번호',
];
