<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Informazioni sul conto',
    'Action' => 'Azione',
    'Add to Cart' => 'Aggiungi al carrello',
    'Address' => 'Indirizzo',
    'Address information' => 'Informazioni sull\'indirizzo',
    'Are you sure you want to remove this product from cart?' => 'Sei sicuro di voler rimuovere questo prodotto dal carrello?',
    'Auth Key' => 'Chiave di autorizzazione',
    'Cart' => 'Carrello',
    'Checkout' => 'Cassa',
    'City' => 'Città',
    'Country' => 'Paese',
    'Created At' => 'Creato a',
    'Created By' => 'Creato da',
    'Delete' => 'Elimina',
    'Description' => 'Descrizione',
    'Email' => 'Email',
    'Firstname' => 'Nome',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'Se hai dimenticato la tua password puoi {0}',
    'Image' => 'Immagine',
    'Is Admin' => 'È Admin',
    'Lastname' => 'Cognome',
    'Login' => 'Login',
    'Logout' => 'Logout',
    'Name' => 'Nome',
    'Need new verification email?' => 'Hai bisogno di una nuova email di verifica?',
    'Order ID' => 'ID ordine',
    'Password' => 'Password',
    'Password Hash' => 'Hash della password',
    'Password Reset Token' => 'Token per la reimpostazione della password',
    'Paypal Order ID' => 'ID ordine Paypal',
    'Please choose your new password:' => 'Per favore scegli la tua nuova password:',
    'Please contact us if you think this is a server error. Thank you.' => 'Per favore contattaci se pensi che questo sia un errore del server. Grazie.',
    'Please fill out the following fields to login:' => 'Compila i seguenti campi per effettuare il login:',
    'Please fill out the following fields to signup:' => 'Compila i seguenti campi per registrarti:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Per favore, compila la tua email. Ti verrà inviato un link per reimpostare la password.',
    'Please fill out your email. A verification email will be sent there.' => 'Per favore, compila la tua email. Un\'email di verifica sarà inviata lì.',
    'Price' => 'Prezzo',
    'Product' => 'Prodotto',
    'Product ID' => 'ID prodotto',
    'Product Image' => 'Immagine del prodotto',
    'Product Name' => 'Nome del prodotto',
    'Products' => 'Prodotti',
    'Profile' => 'Profilo',
    'Published' => 'Pubblicato',
    'Quantity' => 'Quantità',
    'Remember Me' => 'Ricordati di me',
    'Resend' => 'Reinvia',
    'Reset it' => 'Ripristina',
    'Save' => 'Salva',
    'Send' => 'Invia',
    'Signup' => 'Iscriviti',
    'State' => 'Stato',
    'Status' => 'Stato',
    'Thanks for your business' => 'Grazie per il tuo business',
    'The above error occurred while the Web server was processing your request' => 'L\'errore di cui sopra si è verificato mentre il server web stava elaborando la tua richiesta',
    'There are no items in the cart' => 'Non ci sono articoli nel carrello',
    'Total Items' => 'Totale articoli',
    'Total Price' => 'Prezzo totale',
    'Transaction ID' => 'ID transazione',
    'Unit Price' => 'Prezzo unitario',
    'Update' => 'Aggiornamento',
    'Updated At' => 'Aggiornato a',
    'Updated By' => 'Aggiornato da',
    'User ID' => 'ID utente',
    'Username' => 'Nome utente',
    'Verification Token' => 'Token di verifica',
    'Welcome {0}' => 'Benvenuto {0}',
    'Your account was successfully updated' => 'Il tuo account è stato aggiornato con successo',
    'Your address was successfully updated' => 'Il tuo indirizzo è stato aggiornato con successo',
    'Your cart items' => 'I prodotti del tuo carrello',
    'ZipCode' => 'Codice postale',
];
