<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Информация о счете',
    'Action' => 'Действие',
    'Add to Cart' => 'Добавить в корзину',
    'Address' => 'Адрес',
    'Address information' => 'Информация об адресе',
    'Are you sure you want to remove this product from cart?' => 'Вы уверены, что хотите удалить этот товар из корзины?',
    'Auth Key' => 'Ключ авторизации',
    'Cart' => 'Корзина',
    'Checkout' => 'Оформление заказа',
    'City' => 'Город',
    'Country' => 'Страна',
    'Created At' => 'Создан в',
    'Created By' => 'Создан',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Email' => 'Электронная почта',
    'Firstname' => 'Имя пользователя',
    'ID' => 'ID',
    'If you forgot your password you can {0}' => 'Если вы забыли свой пароль, вы можете {0}',
    'Image' => 'Изображение',
    'Is Admin' => 'Администратор',
    'Lastname' => 'Фамилия',
    'Login' => 'Вход',
    'Logout' => 'Выход',
    'Name' => 'Имя',
    'Need new verification email?' => 'Нужен новый проверочный email?',
    'Order ID' => 'Идентификатор заказа',
    'Password' => 'Пароль',
    'Password Hash' => 'Хеш пароля',
    'Password Reset Token' => 'Токен сброса пароля',
    'Paypal Order ID' => 'Идентификатор заказа Paypal',
    'Please choose your new password:' => 'Пожалуйста, выберите новый пароль:',
    'Please contact us if you think this is a server error. Thank you.' => 'Пожалуйста, свяжитесь с нами, если вы считаете, что это ошибка сервера. Спасибо.',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните следующие поля для входа в систему:',
    'Please fill out the following fields to signup:' => 'Пожалуйста, заполните следующие поля для регистрации:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Пожалуйста, заполните свой e-mail. На него будет отправлена ссылка для сброса пароля.',
    'Please fill out your email. A verification email will be sent there.' => 'Пожалуйста, заполните свой e-mail. На него будет отправлено письмо для проверки.',
    'Price' => 'Цена',
    'Product' => 'Продукт',
    'Product ID' => 'Идентификатор продукта',
    'Product Image' => 'Изображение продукта',
    'Product Name' => 'Название продукта',
    'Products' => 'Продукты',
    'Profile' => 'Профиль',
    'Published' => 'Опубликовано',
    'Quantity' => 'Количество',
    'Remember Me' => 'Помни меня',
    'Resend' => 'Повторно отправить',
    'Reset it' => 'Сбросить',
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Signup' => 'Регистрация',
    'State' => 'Государство',
    'Status' => 'Статус',
    'Thanks for your business' => 'Спасибо за ваш бизнес',
    'The above error occurred while the Web server was processing your request' => 'Приведенная выше ошибка произошла во время обработки веб-сервером вашего запроса',
    'There are no items in the cart' => 'В корзине нет товаров',
    'Total Items' => 'Всего товаров',
    'Total Price' => 'Общая цена',
    'Transaction ID' => 'Идентификатор транзакции',
    'Unit Price' => 'Цена единицы товара',
    'Update' => 'Обновить',
    'Updated At' => 'Обновлено в',
    'Updated By' => 'Обновлено по',
    'User ID' => 'Идентификатор пользователя',
    'Username' => 'Имя пользователя',
    'Verification Token' => 'Токен верификации',
    'Welcome {0}' => 'Добро пожаловать {0}',
    'Your account was successfully updated' => 'Ваш аккаунт был успешно обновлен',
    'Your address was successfully updated' => 'Ваш адрес был успешно обновлен',
    'Your cart items' => 'Ваши товары в корзине',
    'ZipCode' => 'ZipCode',
];
