<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account information' => 'Thông tin tài khoản',
    'Action' => 'Hoạt động',
    'Add to Cart' => 'Thêm vào giỏ hàng',
    'Address' => 'Địa chỉ',
    'Address information' => 'Thông tin địa chỉ',
    'Are you sure you want to remove this product from cart?' => 'Bạn có chắc chắn muốn xóa sản phẩm này khỏi giỏ hàng không?',
    'Auth Key' => 'Khóa xác thực',
    'Cart' => 'xe đẩy',
    'Checkout' => 'Thủ tục thanh toán',
    'City' => 'Tp.',
    'Country' => 'Quốc gia',
    'Created At' => 'Được tạo lúc',
    'Created By' => 'Được tạo bởi',
    'Delete' => 'Xóa bỏ',
    'Description' => 'Sự miêu tả',
    'Email' => 'E-mail',
    'Firstname' => 'Tên đầu tiên',
    'ID' => 'TÔI',
    'If you forgot your password you can {0}' => 'Nếu bạn quên mật khẩu của mình, bạn có thể {0}',
    'Image' => 'Hình ảnh',
    'Is Admin' => 'Là quản trị viên',
    'Lastname' => 'Họ',
    'Login' => 'Đăng nhập',
    'Logout' => 'Đăng xuất',
    'Name' => 'Tên',
    'Need new verification email?' => 'Cần email xác minh mới?',
    'Order ID' => 'ID đặt hàng',
    'Password' => 'Mật khẩu',
    'Password Hash' => 'Băm mật khẩu',
    'Password Reset Token' => 'Mã thông báo đặt lại mật khẩu',
    'Paypal Order ID' => 'ID đơn đặt hàng Paypal',
    'Please choose your new password:' => 'Vui lòng chọn mật khẩu mới của bạn:',
    'Please contact us if you think this is a server error. Thank you.' => 'Vui lòng liên hệ với chúng tôi nếu bạn cho rằng đây là lỗi máy chủ. Cảm ơn bạn.',
    'Please fill out the following fields to login:' => 'Vui lòng điền vào các trường sau để đăng nhập:',
    'Please fill out the following fields to signup:' => 'Vui lòng điền vào các trường sau để đăng ký:',
    'Please fill out your email. A link to reset password will be sent there.' => 'Vui lòng điền vào email của bạn. Một liên kết để đặt lại mật khẩu sẽ được gửi đến đó.',
    'Please fill out your email. A verification email will be sent there.' => 'Vui lòng điền vào email của bạn. Một email xác minh sẽ được gửi đến đó.',
    'Price' => 'Giá bán',
    'Product' => 'Sản phẩm',
    'Product ID' => 'ID sản phẩm',
    'Product Image' => 'Hình ảnh sản phẩm',
    'Product Name' => 'tên sản phẩm',
    'Products' => 'Các sản phẩm',
    'Profile' => 'Hồ sơ',
    'Published' => 'Được phát hành',
    'Quantity' => 'Định lượng',
    'Remember Me' => 'Nhớ tôi',
    'Resend' => 'Gửi lại',
    'Reset it' => 'Đặt lại nó',
    'Save' => 'Tiết kiệm',
    'Send' => 'Gửi',
    'Signup' => 'Đăng ký',
    'State' => 'Tiểu bang',
    'Status' => 'Trạng thái',
    'Thanks for your business' => 'Cảm ơn Doanh nghiệp của bạn',
    'The above error occurred while the Web server was processing your request' => 'Lỗi trên xảy ra khi máy chủ Web đang xử lý yêu cầu của bạn',
    'There are no items in the cart' => 'Không có mặt hàng trong giỏ hàng',
    'Total Items' => 'Tổng số mặt hàng',
    'Total Price' => 'Tổng giá',
    'Transaction ID' => 'ID giao dịch',
    'Unit Price' => 'Đơn giá',
    'Update' => 'Cập nhật',
    'Updated At' => 'Cập nhật tại',
    'Updated By' => 'Cập nhật',
    'User ID' => 'Tên người dùng',
    'Username' => 'tên tài khoản',
    'Verification Token' => 'Mã xác minh',
    'Welcome {0}' => 'Chào mừng {0}',
    'Your account was successfully updated' => 'Tài khoản của bạn đã được cập nhật thành công',
    'Your address was successfully updated' => 'Địa chỉ của bạn đã được cập nhật thành công',
    'Your cart items' => 'Các mặt hàng trong giỏ hàng của bạn',
    'ZipCode' => 'Mã Bưu Chính',
];
